### ISSUE TITLE
Installation instructions don't work. 

### ISSUE THREAD

**Issue by sdm7g** [cul/hyacinth#2]
rake hyacinth:setup:config_files  fails with:

     rake aborted!
     NameError: undefined local variable or method  'uri_service' for main:Object
     /Users/sdm7g/hyacinth/lib/tasks/hyacinth/setup.rake:85:in 'block (4 levels) in <top (required)>'
     /Users/sdm7g/hyacinth/lib/tasks/hyacinth/setup.rake:82:in 'each'
     /Users/sdm7g/hyacinth/lib/tasks/hyacinth/setup.rake:82:in 'block (3 levels) in <top (required)>'

I removed `+ uri_service`  from line 85:
https://github.com/cul/hyacinth/blob/master/lib/tasks/hyacinth/setup.rake#L85
so it matches line 73 above it:
https://github.com/cul/hyacinth/blob/master/lib/tasks/hyacinth/setup.rake#L73

hyacinth:setup:config_files task will then complete without error and produce a config/uri_service.yml file.  db:migrate and jetty tasks are successful. 

####  I'm running java 1.7, so that may be the reason for the following issues: 
Will see if I can try with 1.8 

rake hyacinth:fedora:reload_cmodels fails:

    ---------------------------
    Fedora URL: http://localhost:8983/fedora
    Solr URL: http://localhost:8983/solr/development
    ---------------------------
    possible problem with purge of ldpd:nullbind: 503 Service Unavailable
    possible problem with ingest of ldpd:nullbind: 503 Service Unavailable
    rake aborted!
    RestClient::ServiceUnavailable: 503 Service Unavailable

db:seed also fails with `RestClient::ServiceUnavailable: 503 Service Unavailable`
Solr admin interface and cores respond. Fedora appears to be the one that's unavailable. 
There were no errors from jetty:start and nothing in the jetty/logs except an empty 'dummy' file. 
The rails app can run and I can log in to it, but I don't know how functional it is without Fedora.

**Comment by elo2112** [comment]
Can you try setting things up again with the latest version of master?  I accidentally brought some incomplete changes in during that commit.

**Comment by sdm7g** [comment]
OK: It works for me up to the rake hyacinth:fedora:reload_cmodels and I believe that must be due to my trying it with java 1.7.  I see the logs are actually in jettywrapper.log , which has some errors:

    Caused by: java.lang.UnsupportedClassVersionError:   org/fcrepo/server/utilities/LogSetupContextListener : Unsupported major.minor version 52.0
    17:47:42.227 [main] DEBUG o.e.jetty.webapp.WebAppClassLoader - loaded class java.lang.Error
    17:47:42.227 [main] DEBUG o.e.jetty.webapp.WebAppClassLoader - loaded class java.lang.Error from null
    17:47:42.238 [main] DEBUG o.e.jetty.webapp.WebAppClassLoader - loaded class java.lang.NoClassDefFoundError


( Will try again with 1.8 if I can install it without breaking my other java apps. )

**Comment by elo2112** [comment]
Thanks for the update.  You're right about the Java 8 requirement.  That's because I'm using the latest version of hydra-jetty, which includes Fedora 3.8.1.  I'm pretty sure that Fedora 3.8.1 only runs under Java 8.

As an alternative, you can swap out the hydra-jetty Fedora / Solr instances for your own instances.  That eliminates the Java 8 dependency for running the app, but the CI tests will still require Java 8 (again because of hydra-jetty/Fedora 3.8.1).

**Comment by sdm7g** [comment]
Does something else have to be done to start the repository_cache server at 3001 ? 
None of the thumbnails display and they have URLs using that port. 

Also: all URLs in config yml files are to `localhost` . 
Some of those are for internal links and are OK, but some others (like those localhost:3001 thumbnails) are propagated by the browser, and break when browser and server aren't the same host.

**Comment by elo2112** [comment]
Ah, right.  Sorry, I forgot to include a reference to the repository_cache app in the README.  It's a separate application that we developed at Columbia, but it's currently in a private repo.  You're right, thumbnails can't be generated without it.  My team needs to work some things out before releasing it publicly, but I may break out some of the functionality into Hyacinth (or into a gem) before that time.  I'm not sure how soon I'll have a chance to do that (due to competing priorities), but I'll update the README to let people know that thumbnails can't currently be tested.
